version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: pgvector/pgvector:0.7.2-pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "6024:5432"
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
